### ISSUE TITLE
amgtar DAR restores do not work with dumps larger than INT_MAX bytes due to use of int type

### ISSUE THREAD

**Issue by skysyzygy** [zmanda/amanda#156]
Restores (amfetchdump, amrecover) that use state-file positioning / direct access recovery and which are from dumps larger than INT_MAX bytes will not be correctly restored by amgtar because the amgtar_restore uses a signed short int type for storing the previous block. 

A long int would do fine, or off_t just to be safe...

**Comment by chassell** [comment]
Is this really it?  It's the only thing related to the restore.

```
--- a/application-src/amgtar.c
+++ b/application-src/amgtar.c
@@ -1839,7 +1839,7 @@ amgtar_restore(
                fprintf(dar_file,"DAR 0:-1\n");
                g_debug("full dar: 0:-1");
            } else {
-               int   previous_block = -1;
+               off_t   previous_block = -1;
 
                while (fgets(line, 32768, recover_state_file) != NULL) {
                    off_t     block_no = g_ascii_strtoull(line, NULL, 0);
```

**Comment by jolson-bam** [comment]
Yes!!! That was my solution as well =)

**Comment by chassell** [comment]
I have a bunch more for that... just to make sure it is 64 bits always.  I'll submit it to this issue.

**Comment by chassell** [comment]
@jolson-bam  tell me what you think.

**Comment by chassell** [comment]
It passes gcc with -Wconversion now, at least.

**Comment by chassell** [comment]
This will be handled in a newer merge.
