### ISSUE TITLE
3_5 overwrites active tapes using lexical or oldest taperscan

### ISSUE THREAD

**Issue by mcdamo** [zmanda/amanda#160]
I found when using the **lexical** or **oldest** taperscan that it readily overwrites an active tape, even overwriting and re-using the same tape for a multi-tape dump.

I built v3.5.1 from [Branch:3_5](/zmanda/amanda/tree/3_5) source, using `chg-single` with a single drive.

Examples below with an active tape that should be rejected by the taperscan:

TRADITIONAL taperscan:
```
% amcheck -s config
slot 1: volume 'Monthly-07' is still active and cannot be overwritten
all slots have been loaded
Taper scan algorithm did not find an acceptable volume.
   (expecting a new volume)
ERROR: No acceptable volumes found
```

LEXICAL/OLDEST taperscan:
```
% amcheck -s config
slot 1: volume 'Monthly-07'
Will write to volume 'Monthly-07' in slot 1.
```

AFAICT 491c63ba1114aba4beba403d9be0c5693331f413 from PR #136 is the cause of this behavior.

**Comment by chassell** [comment]
This seems ... kinda bad.

**Comment by chassell** [comment]
@mcdamo  if you want to look into the pull request, I think it will help.

**Comment by chassell** [comment]
Seems to work fine.
