### ISSUE TITLE
S3 support: Google oauth2 

### ISSUE THREAD

**Issue by rforberger** [zmanda/amanda#190]
I discovered that using the S3 support in Amanda causes the following error sending backups to Google Cloud Storage:

amlabel log file:
```
...
Sun Sep 04 06:53:24.833732403 2022: pid 42080: thd-0x55bef08ebe00: amlabel: Connection #0 to host accounts.google.com left intact
Sun Sep 04 06:53:24.833740449 2022: pid 42080: thd-0x55bef08ebe00: amlabel: data in 75: {
  "error": "unauthorized_client",
  "error_description": "Unauthorized"
}
Sun Sep 04 06:53:24.833758296 2022: pid 42080: thd-0x55bef08ebe00: amlabel: POST https://accounts.google.com/o/oauth2/token failed with 401/None
```

I think the problem is the oauth2 endpoint in the URL where the token is sent to Google.

I guess the right endpoint is: https://www.googleapis.com/oauth2/v4/token. I assume, Google changed this some time ago.

**Comment by rforberger** [comment]
It looks like that this is the commit: https://github.com/zmanda/amanda/commit/ccd530d88a1d1bfa81d83a0804e2153fe76efa6e (11 years ago).

**Comment by stefangweichinger** [comment]
@rforberger no fully on topic: would you share a config example for using GCS with amanda? thanks!

**Comment by rforberger** [comment]
@stefangweichinger 
I think the problem is different. The URL is still valid.
I am getting "Error reading volume label: While creating new S3 bucket: Unknown S3 error (None) (HTTP 401). when running amlabel against GCS.
log file:
```
Sun Sep 04 09:08:45.796733379 2022: pid 69950: thd-0x55ffbd040600: amlabel: data in 75: {
  "error": "unauthorized_client",
  "error_description": "Unauthorized"
}
```
Config:
```
org "config-production"
dumpuser "amandabackup"
logdir "/var/log/amanda"
infofile "/var/lib/amanda/state/curinfo"
indexdir "/var/lib/amanda/state/index"


debug_auth 9
debug_event 9
debug_holding 9
debug_protocol 9
debug_planner 9
debug_driver 9
debug_dumper 9
debug_chunker 9
debug_taper 9

# Google Cloud Storage S3
device_property "S3_ACCESS_KEY" "REDACTED"                # Your S3 Access Key
device_property "S3_SECRET_KEY" "REDACTED"  # Your S3 Secret Key
device_property "S3_SSL" "YES"                                        # Curl needs to have S3 Certification Authority (Verisign today) 
device-property "S3_HOST" "storage.googleapis.com"
#device-property "S3_STORAGE_CLASS" "COLDLINE"
device-property "STORAGE_API" "OAUTH2"
device-property "TIMEOUT" "100"
device-property "VERBOSE" "true"
device-property "PROJECT_ID" "REDACTED"
#device-property "S3_BUCKET_LOCATION" "us-central1"
device-property "CLIENT_ID" "REDACTED.apps.googleusercontent.com"
device-property "CLIENT_SECRET" "REDACTED"
device-property "REFRESH_TOKEN" "REDACTED"

#dumpcycle 3 days
#amrecover_changer "chg-multi"
tapetype S3
tpchanger "chg-multi:s3:amanda-storage-jim/config-production/slot-{01,02,03,04,05,06,07,08,09,10}" 

define changer jim-changer {
    comment "Jim changer"
    changerfile  "s3-statefile"                                           
}

define tapetype S3 {
    comment "S3 Bucket"
    length 10240 gigabytes # Bucket size 10TB
}

define dumptype simple-gnutar-local {
    auth "local"
    compress best
    program "GNUTAR"
}
```
I am not hundred percent sure, if my REFRESH_TOKEN is correct. The GCP documentation is not clear for me here.
Do you know how to exactly generate the REFRESH_TOKEN on GCP?
Any other clues what could be wrong?

**Comment by stefangweichinger** [comment]
@rforberger thanks for sharing, I will try to edit a config here as well. optionally we could talk via email.

I don't have any idea yet how to generate that token, sorry.

Which release of amanda do you use, which distro? I was told that GCS support isn't fully working with releases prior to 3.6 (beta, currently).

**Comment by rforberger** [comment]
@stefangweichinger 
Thanks alot. 
My Amanda version is 3.5.1-35 on Fedora 36.
OK, does it make sense to wait for Amanda 3.6?

**Comment by stefangweichinger** [comment]
@rforberger 

can't tell exactly. That's why I look for working examples ;-)

You only define one storage, right? I would try to define a separate storage definition containing all these device properties etc
Trying to convert your example now.

As far as I understand you weren't able to label or access any virtual tape with this config yet?

**Comment by rforberger** [comment]
@stefangweichinger 
Exactly. I am currently getting the HTTP 401 code from GCP.

**Comment by stefangweichinger** [comment]
>  REFRESH_TOKEN

maybe: 

https://developers.google.com/google-ads/api/docs/first-call/refresh-token

**Comment by rforberger** [comment]
Didn't find it yet. I do not get oauth2 with Amanda running. The refresh_token seems not accepted.
But I tried without oauth2, but then I run into an other error.
The problem seems to be: `amlabel: Hdr Out: authorization: AWS <some_key>` in the amlabel log.
I guess Amanda is sending the wrong HTTP header here?
Maybe I am completely wrong.

The full final log file error is:
```
amlabel: Device s3:amanda-storage-jim/config-production/slot-01 error = 'While writing amanda header: Too many retries; last message was 'S3 Error: Unknown (empty response body)' (None) (CURLcode 92) (HTTP 400) (after 14 retries)'
Sun Sep 04 12:04:08.158759754 2022: pid 105466: thd-0x562d58515e00: amlabel: Device s3:amanda-storage-jim/config-production/slot-01 setting status flag(s): DEVICE_STATUS_DEVICE_ERROR, and DEVICE_STATUS_VOLUME_ERROR
Sun Sep 04 12:04:08.158970969 2022: pid 105466: thd-0x562d58515e00: amlabel: /usr/lib64/perl5/vendor_perl/Amanda/Label.pm:796:error:1000028 Error writing label: While writing amanda header: Too many retries; last message was 'S3 Error: Unknown (empty response body)' (None) (CURLcode 92) (HTTP 400) (after 14 retries).
```

**Comment by stefangweichinger** [comment]
Did you successfully generate that token? I might test things later or tmrw.
Maybe the S3-device isn't fully compatible with current GCP.

**Comment by rforberger** [comment]
I'm not 100% sure if I correctly generated the token. Couldn't understand the GCP documentation fully here.
I was attempting , GCS is fully compatible with S3. Maybe it is not. 
Thank you for testing it.

**Comment by rforberger** [comment]
I found out, testing with another backup solution, that the problem should be on Amanda.

**Comment by stefangweichinger** [comment]
> I found out, testing with another backup solution, that the problem should be on Amanda 3.5.

Ah, sorry to hear. So maybe we have to wait for 3.6 or test with the beta.

**Comment by stefangweichinger** [comment]
Unfortunately there are still no rpms for the beta.

**Comment by rforberger** [comment]
OK, thanks.

**Comment by rforberger** [comment]
Thanks again, I am closing my issue now.
