### ISSUE TITLE
post-host-backup script does not run

### ISSUE THREAD

**Issue by rforberger** [zmanda/amanda#191]
I have configured my Amanda according to the amanda.conf man page to run a shell script after each backup.

My configuration looks like this:

```
org "config-production"
dumpuser "amandabackup"
logdir "/var/log/amanda"
infofile "/amanda/state/curinfo"
indexdir "/amanda/state/index"

debug_auth 9
debug_event 9
debug_holding 9
debug_protocol 9
debug_planner 9
debug_driver 9
debug_dumper 9
debug_chunker 9
debug_taper 9

tpchanger "chg-disk:/amanda/vtapes"
labelstr "data[0-9][0-9]"
autolabel "data%%" EMPTY VOLUME_ERROR
tapecycle 1
dumpcycle 2 days
amrecover_changer "changer"

tapetype "TAPE01"
define tapetype TAPE01 {
  length 299 gbytes
  filemark 4 kbytes
}

define dumptype simple-gnutar-local {
    auth "local"
    compress best
    program "GNUTAR"
    no-hold
    no-full
}

holdingdisk hd1 {
    directory "/amanda/holding"
    use 0 mbytes
    chunksize 1 mbyte
}

define script rclone {
    comment "launch rclone sync"
    execute-on post-host-backup
    execute-where server
    plugin "rclone"
}
```
But my script rclone which resides in /usr/lib64/amanda/applications and is executable by `amandabackup` will not launch.
OS: Fedora 36
Anybody an idea?

**Comment by stefangweichinger** [comment]
You follow https://wiki.zmanda.com/index.php/Script_API ?

I spot "define script" ... the docs say it's "define script-tool my-script"

What does amcheck tell you?

**Comment by rforberger** [comment]
Yes, I followed it.
I tried both `script` and `script-tool`.
amcheck will not tell anything.

**Comment by stefangweichinger** [comment]
In your quoted config you don't call the script from your dumptype.
Check the mentioned docs for "Use the script in a dumptype".

I think you need something like:

```
define dumptype simple-gnutar-local {
    auth "local"
    compress best
    program "GNUTAR"
    script "rclone"
    no-hold
    no-full
}
```

**Comment by stefangweichinger** [comment]
Additionally I am not so sure if that script wouldn't have to be called with several options (see "Script calling convention")

**Comment by rforberger** [comment]
It works to call from dumptype. Very much thanks ;)

**Comment by stefangweichinger** [comment]
ok, great. Will try that myself, I also have some `rclone` to run.

**Comment by stefangweichinger** [comment]
@rforberger would you share your rclone-script?

**Comment by rforberger** [comment]
Sure.
```
#!/bin/bash

/usr/bin/rclone sync --update --exclude=lost+found/ --no-console --transfers 30 --copy-links --log-file=/var/log/rclone.log "/amanda" "config-production:amanda-storage-jim/"
```

**Comment by stefangweichinger** [comment]
nice, thanks. And your setup works as intended: start that script once after all amdumps are done?

**Comment by rforberger** [comment]
It looks like that.
