### ISSUE TITLE
debian 11 package issues

### ISSUE THREAD

**Issue by stefangweichinger** [zmanda/amanda#224]
> you can get 3.5.3 packages here

https://www.zmanda.com/downloads/

sorry, missed the link there

_Originally posted by @prajwaltr93 in https://github.com/zmanda/amanda/issues/214#issuecomment-1583935481_

Tried the debian11-packages on a debian-11.7 server after uninstalling the original debian packages (amanda-server, amanda-client, amanda-common).

The new packages show some different config:

* user "amandabackup", debian packages use "backup"
* `/usr/lib/x86_64-linux-gnu/amanda/amandad` not found: path seems to be different
* `/usr/bin/gzip` is needed .. Debian has it in `/bin/gzip`

Trying to work around these issues by editing xinetd-config etc

I remember having to adjust "amandad_path" for older clients etc

**Comment by ishansinghcms** [comment]
Hi @stefangweichinger, this is regarding the issue that you mentioned. 

The below are the configurations that we use to build our package-
        --libdir=/usr/lib/x86_64-linux-gnu \
        --libexecdir=/usr/lib/x86_64-linux-gnu \
        --with-user=amandabackup \

In the above configurations, you can observe the following points- 

- the user that is created is "amandabackup" and not "backup".
- architecture-dependent libraries are included in path "/usr/lib/x86_64-linux-gnu", so amandad daemon will be located under this directory only.
- gzip utility in debian 11.7 is also located in "/usr/bin/gzip" and not "/bin/gzip".

I installed the same version of binary (3.5.3) on Debian 11.7 and didn't face any such issues. If you are still facing this issue, could you please provide the configurations that you are using?

Thank You

**Comment by stefangweichinger** [comment]
@ishansinghcms thanks for asking. Quite busy here, I'd have to see in which test VM I tried that and recheck my steps.
Currently it's not an issue for me: no package building for me right now :-)

Maybe you share your full configure-command as a reference, thanks.

**Comment by ishansinghcms** [comment]
Hi @stefangweichinger, the full configure-command is mentioned below-

./configure \
        MAKEFLAGS="-j1 " \
        CFLAGS="-pipe " \
        MAILER=/usr/bin/mail \
        --enable-as-needed \
        --enable-manpage-build \
        --quiet \
        --host=x86_64-linux-gnu \
        --build=x86_64-linux-gnu \
        --prefix=/usr \
        --libdir=/usr/lib/x86_64-linux-gnu \
        --bindir=/usr/bin \
        --mandir=/usr/share/man \
        --libexecdir=/usr/lib/x86_64-linux-gnu \
        --enable-shared \
        --sysconfdir=/etc \
        --localstatedir=/var \
        --with-amdatadir=/var/lib/amanda \
        --with-gnutar-listdir=/var/lib/amanda/gnutar-lists \
        --with-index-server=localhost \
        --with-tape-server=localhost \
        --with-user=amandabackup \
        --with-group=disk \
                --with-fqdn \
        --with-bsd-security \
                --with-bsdtcp-security \
                --with-bsdudp-security \
        --with-amandahosts \
        --with-smbclient=/usr/bin/smbclient \
        --with-debugging=/var/log/amanda \
        --with-ssh-security \
        --with-assertions \
        --enable-s3-device \
        --disable-installperms

**Comment by BhaveshSP** [comment]
Thank you for raising this issue. It appears that the original reporter is no longer active, and we haven't received any updates or additional information. As a result, we are closing this issue. 

If you encounter similar issues or have further questions in the future, please feel free to open a new issue.
