### ISSUE TITLE
Is there a procedure documented to recover an amanda backup server from scratch if I have all my backup tapes?

### ISSUE THREAD

**Issue by douginoz** [zmanda/amanda#245]
If the server running amanda server on it blows up, I need to know how to recover it once I've rebuilt the server.  

I know that I'd first rebuild the server and install the o/s then install amanda, but after that it seems less well defined what is required.  Most wiki articles assume a working amanda backup server so that normal amanda commands can be issued.  But none of those commands (amrecover, etc.) will work on a totally blank server that is just the o/s + brand new virgin unconfigured amanda on it.  None of the config, logs, etc. would be available.  

If I have a complete full backup, then I want to document the steps needed to restore my system from those tapes.  Ideally using amanda of course. I know I could just read the tapes manually but that defeats the point of using amanda to begin with.

I'm aware that the first 32k of each tape file (file header) contains DLE, dump level and datestamp. It also contains the command that can be used to restore the dump.  So is that the only/best recovery procedure?  Rebuild the server, install amanda backup, then read the tape(s) to get the 32K block that includes how to restore the dump, then issue that command?

I would have thought a better approach would be to back up specific amanda folders to a safe location _before_ a crash occurs so that they can be copied back afterwards, thus allowing a simple amrecover to run.  But there are several folders on my ubuntu system and amanda has data across many locations - /var/log/amanda, /etc/amanda, etc.  There may be more.  I could hunt around to try to find them but if I miss any and can't recover when I need to most, I'll be wishing I'd logged this request!

I've looked for a comprehensive list of the locations of all Amanda data on a given (linux/ubuntu/debian) system so that I can back those up separately, but I could'nt find one.  I'm assuming this is a well known procedure that hopefully others can point me to.

**Comment by konidev20** [comment]
Hey @douginoz, 

> If the server running amanda server on it blows up, I need to know how to recover it once I've rebuilt the server.

Please check this article out : [When Bad Things Happen to Good Amanda Backup Servers](https://www.zmanda.com/wp-content/uploads/2020/03/When_bad_things_happen_to_good_Amanda_backup_Servers.pdf)

This is the best guide to backing up Amanda Backup Servers and restoring them. I will be happy to help you with anything else.
