### ISSUE TITLE
Support to install on Rocky Linux 9

### ISSUE THREAD

**Issue by lexcorp** [zmanda/amanda#247]
I'm trying to install amanda community on Rocky Linux. But unfortunately, the package manager doesn't find some dependencies:

**sudo rpm -ihv amanda-backup_server-3.5.4.git.0da4f0ee-1.rhel7.x86_64.rpm** 

error: Error de dependencias:
	xinetd es necesario por amanda-backup_server-3.5.4.git.0da4f0ee-1.rhel7.x86_64
	libcrypto.so.10()(64bit) es necesario por amanda-backup_server-3.5.4.git.0da4f0ee-1.rhel7.x86_64
	libcrypto.so.10(libcrypto.so.10)(64bit) es necesario por amanda-backup_server-3.5.4.git.0da4f0ee-1.rhel7.x86_64
	libreadline.so.6()(64bit) es necesario por amanda-backup_server-3.5.4.git.0da4f0ee-1.rhel7.x86_64
	libssl.so.10()(64bit) es necesario por amanda-backup_server-3.5.4.git.0da4f0ee-1.rhel7.x86_64
	libssl.so.10(libssl.so.10)(64bit) es necesario por amanda-backup_server-3.5.4.git.0da4f0ee-1.rhel7.x86_64
	libtirpc.so.1()(64bit) es necesario por amanda-backup_server-3.5.4.git.0da4f0ee-1.rhel7.x86_64

![](https://i.imgur.com/bxMmSba.png)

https://forums.rockylinux.org/t/xinetd-rpm-for-rockylinux-9/10279

_xinetd is long gone in 9. You will need to setup systemd socket services instead._

https://forums.rockylinux.org/t/libcrypto-and-libssl-not-found/11348

_libcrypto.so.10 only exists on Rocky Linux 8. Rocky Linux 9 does not have that package._

That means restarting the whole installation with Rocky Linux 8.

**Comment by konidev20** [comment]
Hey @lexcorp, I can try get you systemd service file and socket service files for the `amandad` server and client. 

As for the `libcrypto.so.10` dependency, I will check how the enterprise version of the application supports Rocky Linux 9 and above.

PS: Happy New Year :)

**Comment by opoplawski** [comment]
Why not install amanda from EPEL?

**Comment by lexcorp** [comment]
> Why not install amanda from EPEL?

Because version in EPEL is 3.5.3

**Comment by opoplawski** [comment]
I would suggest filling an issue here https://bugzilla.redhat.com/enter_bug.cgi?product=Fedora%20EPEL requesting that it be updated then.

**Comment by lexcorp** [comment]
Thanks @opoplawski
