### ISSUE TITLE
3.5.4 -- ndmp-src/ndmprotocol.h calls nonexistant ndmp0.h

### ISSUE THREAD

**Issue by hymie0** [zmanda/amanda#249]
ndmp-src/ndmprotocol.h includes these lines

```
#include "ndmp0.h"

#ifndef NDMOS_OPTION_NO_NDMP2
#include "ndmp2.h"
#endif /* !NDMOS_OPTION_NO_NDMP2 */

#ifndef NDMOS_OPTION_NO_NDMP3
#include "ndmp3.h"
#endif /* !NDMOS_OPTION_NO_NDMP3 */

#ifndef NDMOS_OPTION_NO_NDMP4
#include "ndmp4.h"
#endif /* !NDMOS_OPTION_NO_NDMP4 */

#include "ndmp9.h"
```

but none of these files exist in the source tree.

**Comment by konidev20** [comment]
Hey @hymie0, 

You require the following build dependencies:
**Ubuntu/Debian based**
```
sudo apt install libtirpc3
```

**RHEL/Rocky Linux 8 and RPM based**
```
sudo yum install libtirpc
```
and `rpcgen` from `epel-release`

here's what worked for me when I started to check this out
```
sudo dnf install epel-release
sudo dnf config-manager --set-enabled powertools
sudo dnf update
sudo dnf rpcgen
```

I have documented some of my findings to be updated on the documentation in here: [https://github.com/konidev20/explore-amanda/tree/main/guides](https://github.com/konidev20/explore-amanda/tree/main/guides)

Do let me know if its' helpful.

[Development Dependencies | Wiki Zmanda](https://wiki.zmanda.com/index.php/Development_Dependencies) 

PS: This needs to be updated.

**Comment by hymie0** [comment]
I am neither Ubuntu nor RedHat. I am Slackware.
I have tirpc and rpcgen installed, but neither of those packages include the ndmp0.h nmdp2.h etc files that used to appear inside the ndmp-src directory.
I ended up building --without-ndmp

**Comment by konidev20** [comment]
> I am neither Ubuntu nor RedHat. I am Slackware. I have tirpc and rpcgen installed, but neither of those packages include the ndmp0.h nmdp2.h etc files that used to appear inside the ndmp-src directory. I ended up building --without-ndmp

Okay, `--without-ndmp` means you will not be able to back up to tape.

**Comment by konidev20** [comment]
There are no pending action items from our end.
