### ISSUE TITLE
Recommended Way to Report a Potential Security Issue

### ISSUE THREAD

**Issue by jslarraz** [zmanda/amanda#250]
Hi amanda team 👋,

Could you please advise me where I should report a bug that may have a security impact? Unfortunately, there are no security policy or recommendations in README.md.

**Comment by konidev20** [comment]
Hey @jslarraz, 

You can use https://github.com/zmanda/amanda/security to report potential security vulnerabilities.

[Edit] I will create a commit to create a SECURITY.md file to highlight the process [/Edit]

Thanks,

**Comment by jslarraz** [comment]
Thanks! @konidev20
