### ISSUE TITLE
amrecover fail with utf-8 filename

### ISSUE THREAD

**Issue by martineau** [zmanda/amanda#36]
all non-ASCII characters are in octal representation (\000) in the index file.
amrecover is run in the user locale, it should be able to display characters in user locale
On recovery, the application is also run in the C locale, but can it accept non-ASCII characters? some can and some can't.
That's why the patch can't be committed.
Also, it can be possible to have filename in a different locale, using the root locale to display them can make it harder.

We should add an amrecover setting that enable the translation of an octal representation to a single bytes.

There is a workaround, octal characters must be preceded by 4 backslash:
amrecover> add \\303\\275

**Comment by chassell** [comment]
we've seen successful utf8 storage / restore of files... do I'll close this.
