### ISSUE TITLE
Exclude in dumptype using app_amsamba does not work

### ISSUE THREAD

**Issue by platbr** [zmanda/amanda#47]
There is a issue with "exclude" in a dumptype using app_amsamba.
Does not matter what you put in exclude this never match.
I fixed this adding the "r" for tar (smbclient internal command) in app_amsamba.

Now i can use in my dumptype:
exclude "\\dir\\subdir\*.pdf"
exclude append "\\dir\\subdir\\avoid_"
exclude append "\\dir\\subdir\\table?of?values_"

? and \* are the valid wildcards, ? is a good idea for spaces.

Change /usr/libexec/amanda/application/amsamba
Replace:           $comm .= "X";
With:           $comm .= "rX";

Add this line:      return if $line =~ /^tar_re_search/;
Like this:
return if $line =~ /^tarmode is now /;
return if $line =~ /^tar_re_search/;
if ($line =~ /dumped (\d+) files and directories/) {

I tried paste a diff file but didint work here.

Wagner Caixeta Rodrigues
wagner {dot} caixeta {in} gmail {dot} com

**Comment by chassell** [comment]
seems complete.
