### ISSUE TITLE
Disable reverse DNS lookup when auth=ssh

### ISSUE THREAD

**Issue by zazabe** [zmanda/amanda#63]
Hi, 

There's no security reason to do the reverse DNS lookup when the authentication used is SSH, because the security is based on asymmetric keys and not on the DNS resolution at all.

Please check [this thread](https://forums.zmanda.com/showthread.php?5642-Issues-with-SSH-auth-custom-port-and-NAT-network) to get more details about issues with reverse DNS lookup.

In this thread, @martineau propose me a patch that is working perfectly in my case.

I think it can be great to include an option to disable the reverse DNS lookup, or maybe disable it when the auth=SSH.

**Comment by martineau** [comment]
The patch is commited

**Comment by thuandt** [comment]
This patch is not include in `3.3.7` release right?

**Comment by martineau** [comment]
no, 3.3.7 was released before the patch was committed
