### ISSUE TITLE
amreport BEGIN failure

### ISSUE THREAD

**Issue by brettowe** [zmanda/amanda#64]
after first getting a segfault, I recompiled due to perl update in arch linux i get the following now:

Can't use 'defined(@array)' (Maybe you should just omit the defined()?) at /usr/share/perl5/site_perl/Amanda/Report/human.pm line 1203.
Compilation failed in require at (eval 13) line 1.
BEGIN failed--compilation aborted at (eval 13) line 1.

perl -v returns 
This is perl 5, version 22, subversion 0 (v5.22.0) built for x86_64-linux-thread-multi

**Comment by martineau** [comment]
Which version of amanda are you using? What is line 1203 of human.pm in your version?
Since you use github, please recompile the HEAD of the branch, it's probably already fixed.

**Comment by brettowe** [comment]
version I'm running is 3.3.7p1
and I skimmed the commits and I didn't see anything that might help

line 1203 looks like: 
my $to_report = !defined @$tries;

**Comment by martineau** [comment]
Look at commit 21a6a24c in the 3_3 branch
https://github.com/zmanda/amanda/commit/21a6a24c3e51c6005547ada0c441a306ff3668a9

**Comment by brettowe** [comment]
I apparently didn't look at the 3_3 branch when I looked
that commit does resolve my problem
thanks
