### ISSUE TITLE
amdump Progress bar

### ISSUE THREAD

**Issue by jadenyjw** [zmanda/amanda#72]
When amdump is entered into the console, there is no indication of progress in backup.
Would it be possible to implement a progress bar (such as the one in wget, apt-get, etc.) that can display time remaining and percentage?

**Comment by fuzzynoise** [comment]
This can be done by any script polling and parsing e.g. amstatus output at a set interval. I don't know if you've ever watched a progress bar...but there are probably better things to do. If you require a prototype for this exact problem please contact me.

**Comment by chassell** [comment]
would be nice and so will leave, for someday.

**Comment by fuzzynoise** [comment]
It's already part of Amanda Toys. It's called "amwatch" you can check it out, if you like.

**Comment by chassell** [comment]
Then let's leave this closed as a 3 year old problem-with-solution.

**Comment by fuzzynoise** [comment]
Emoji for a thumbs up.
