### ISSUE TITLE
numerous rpmlint warnings binary-or-shlib-calls-gethostbyname

### ISSUE THREAD

**Issue by deadpoint** [zmanda/amanda#75]
rpmlint checks from the opensuse build service are throwing the following warning to port code to getaddrinfo().

[  329s] amanda.x86_64: I: binary-or-shlib-calls-gethostbyname /usr/sbin/amoldrecover
[  329s] amanda.x86_64: I: binary-or-shlib-calls-gethostbyname /usr/sbin/amrecover
[  329s] amanda.x86_64: I: binary-or-shlib-calls-gethostbyname /usr/lib64/amanda/libndmlib-3.3.9.so
[  329s] The binary calls gethostbyname(). Please port the code to use getaddrinfo().

**Comment by chassell** [comment]
To be portable ... we need to deal with some of the older systems, too.   Best attempts over time.
