### ISSUE TITLE
How to use chg-manual

### ISSUE THREAD

**Issue by andyneff** [zmanda/amanda#81]
Starting with Amanada 3.4.0, it looks like the old Amanda Changer v1 API was removed and replaced with the v2 perl changers.

Does [this](https://github.com/zmanda/amanda/blob/ce9c19ca8e8ddd3004348b5d00fa32ed28090c18/perl/Amanda/Changer/single.pm#L44) mean it is not currently possible, or am I missing something?

### Workaround ###

I currently went back to 3.3.9 to get  chg-manual working.

**Comment by martineau** [comment]
Use the chg-single as describe in http://wiki.zmanda.com/man/3.4/amanda-changers.7.html
and setup an interactivity as describe in http://wiki.zmanda.com/man/3.4/amanda-interactivity.7.html

**Comment by andyneff** [comment]
I will give that a shot. thanks!

**Comment by andyneff** [comment]
If I understand it correctly, I added this in my amanda.conf file

```nginx
define changer hpdrive {
  tpchanger "chg-single:/dev/nst0"
}
tpchanger "hpdrive"

define interactivity "email-change" {
  comment "Send email to have tapes swapped"
  plugin "email"
  property "mailto" "me@example.com"
  property "resend-delay" "43200"
}

interactivity "email-change"
```

And when I go to run `amcheck myconfig` I get

```bash
Amanda Tape Server Host Check
-----------------------------
NOTE: Holding disk '/holding/hd1': 1728 GB disk space available, using 1728 GB
slot 1: volume 'mydata-4' is still active and cannot be overwritten
all slots have been loaded
Taper scan algorithm did not find an acceptable volume.
    (expecting a new volume)
ERROR: No acceptable volumes found
Server check took 2.841 seconds
Amanda Backup Client Hosts Check
--------------------------------
Client check: 1 host checked in 0.687 seconds.  0 problems found.
(brought to you by Amanda 3.4.5)
```

And no email.

In 3.3.9, when using `chg-manual`, an `amcheck` would have resulted in an email and waited for me to change the tape, and results in a all successful `amcheck`

```
Amanda Tape Server Host Check
-----------------------------
Holding disk /holding/hd1: 1731 GB disk space available, using 1731 GB
slot 2: volume 'mydata-3' is still active and cannot be overwritten
parent: reaped bogus pid 142
slot 3: volume 'mydata-4'
Will write to volume 'mydata-4' in slot 3.
NOTE: skipping tape-writable test
Server check took 153.844 seconds

Amanda Backup Client Hosts Check
--------------------------------
Client check: 1 host checked in 2.157 seconds.  0 problems found.

(brought to you by Amanda 3.3.9)
```

Of course the success of `amcheck` in not my concern. It was just a good indicator for me that once I fill the tape, it will ask me to change tapes and continue rather than error out.

It takes me an entire week to fill a 15TB tape, so debugging this problem is becoming difficult to test. I have a 30-40 TB DLE and only 15TB tapes, and one tape drive drive, and I'm more than happy to manually change the tapes. So the initial backup will absolutely require a tape change. Is there a change that these setting will indeed work (I already have splitting/spanning setup, etc...), or is my `amcheck` a good indicator that I still have it configured incorrectly?

**Comment by martineau** [comment]
The Interactivity doesn't works with the default traditional tapersan (man amanda-taperscan)
You must configure either the lexical or oldest taperscan:

define taperscan lexical-scan {
  plugin "lexical"
}
taperscan "lexical-scan"

**Comment by andyneff** [comment]
Thanks @martineau! You gave me the last two missing steps!

It's not quite as smooth as the old `chg-manual` that auto ejected the tape and auto continued when I inserted an appropriate tape. I take it that if I wanted that level of customization I'd have to edit my [email.pm](https://github.com/zmanda/amanda/blob/tags/community_3_4_5/perl/Amanda/Interactivity/email.pm) locally.

**Comment by martineau** [comment]
For the eject issue, you can try to set eject-volume to yes in amanda.conf
What do you need to do to continue when a new tape is inserted? It should be automatic.

**Comment by andyneff** [comment]
I already did try setting eject-volume to yes, it did not make a difference

~~You'll have to forgive me, for I do not know perl, however [this](https://github.com/zmanda/amanda/blob/tags/community_3_4_5/perl/Amanda/Interactivity/email.pm#L235) line is the one responsible for polling the `check_file` for touch/updates. And if no file was se [here](https://github.com/zmanda/amanda/blob/tags/community_3_4_5/perl/Amanda/Interactivity/email.pm#L253), then it never enters any sort of polling look for the new tape~~

It did not continue automatically when a new tape was inserted. But it did when I touched the file as documented.

**Comment by martineau** [comment]
the eject-volume work only when running amdump.
What re you doing and what do you expect?

Try the following pull request, it should detect a new tape was inserted:
https://github.com/zmanda/amanda/pull/82

**Comment by andyneff** [comment]
Perfect! :metal: I tested those out against the 3.4.5 branch and everything worked as expected!

Now to do an actual back up some data... it'll only take a month ;)

Thanks @martineau

**Comment by andyneff** [comment]
And it all worked perfectly! 😁
