### ISSUE TITLE
No return in nonvoid functions val_t_to_sv() and val_t_to_print()

### ISSUE THREAD

**Issue by kstreitova** [zmanda/amanda#83]
During the build of amanda package (Amanda 3.5) for openSUSE Tumbleweed we bumped into the following error:

[   81s] I: Program returns random data in a function
[   81s] E: amanda no-return-in-nonvoid-function Amanda/Config.c:1848, 2261

For the current master, it means missing return value in the "fail:" block for the following functions:

static int val_t_to_sv(val_t *val, SV **results) 
https://github.com/zmanda/amanda/blob/master/perl/Amanda/Config.swg#L923

static int val_t_to_print(val_t *val, SV **results)
https://github.com/zmanda/amanda/blob/master/perl/Amanda/Config.swg#L1363

Thanks for fixing it.

**Comment by martineau** [comment]
SWIG_croak_null never return

**Comment by chassell** [comment]
answered and closing now
