### ISSUE TITLE
Zmanda REST-API errror

### ISSUE THREAD

**Issue by Chetu-S-A** [zmanda/amanda#84]
Hi, I complied and installed amanda on my gnu-linux system. 
When I try to run the REST-API-Server, I am getting the following error.

$amanda-rest-server start
The REST-API-PORT must be defined in the global amanda.conf (/usr/local/etc/amanda/amanda.conf) and be larger than 1024

I tried looking for the file in /usr/local/etc/amanda/ but amanda.conf does not exist. I tried adding the REST-API-PORT in the amanda-security.conf but it does not work. I even created a file called amanda.conf in the same path, but the rest server did not start.
Can someone please help me out.

**Comment by martineau** [comment]
Do you get the same error after adding the REST-API-PORT in /usr/local/etc/amanda/amanda.conf?
Can you attach your  /usr/local/etc/amanda/amanda.conf?
Can you also attach the amanda-rest-server.<TIMESTAMP>.debug and amrest-server.<TIMESTAMP>.debug files

**Comment by Chetu-S-A** [comment]
The file does not exist.. I created the file with just this:
REST-API-PORT=8000,8080

But it did not work. If there is a sample file or an ideal file, it would be of great help if you can provide it.

**Comment by djmitche** [comment]
The file it's talking about is your main `amanda.conf` file -- you can't run Amanda without that.  Since you say GNU Linux, is that file perhaps in `/etc/amanda`?  If so, then the compiled REST API server has the wrong idea of where to look for configuration.

Try

```shell
find /etc -name amanda.conf
```

**Comment by martineau** [comment]
There is no '=' in amanda.conf, and only one port number is allowed, try with:
REST-API-PORT 8000

**Comment by martineau** [comment]
I committed the folowing text in the amanda.conf man page:
       rest-api-port int
           No default. The port number the rest server will listen to, it must
           be an unused port.
       
           Must be set in the global amanda.conf file, default to
           /etc/amanda/amanda.conf

**Comment by Chetu-S-A** [comment]
Thank you for your response. 
I created the amanda.conf file in /usr/local/etc/amanda and tried running amanda-rest-server start.
Now it says
"Unable to start Amanda REST server".
Should I start a service before trying to run the Rest Server?

**Comment by martineau** [comment]
Look at the debug file, it should tell you why it didn't start

**Comment by Chetu-S-A** [comment]
Hi. Can you please tell me the location of the debug file?

**Comment by martineau** [comment]
I don't know how you build amanda, you can find it with:
$ man amgetconf
$ amgetconf build --list
$ amgetconf build.amanda_dbgdir

**Comment by Chetu-S-A** [comment]
Hi, 
I followed this guide.
https://wiki.zmanda.com/index.php/Installation/Installing_Amanda_Source
The debug file says:

Mon Jan 15 19:14:50.360734048 2018: pid 2085: thd-0x1a24000: amanda-rest-server: pid 2085 ruid 1000 euid 1000 version 4.0.0alpha.git.d60c8612: start at Mon Jan 15 19:14:50 2018
Mon Jan 15 19:14:50.360901086 2018: pid 2085: thd-0x1a24000: amanda-rest-server: Arguments: start
Mon Jan 15 19:14:50.361093225 2018: pid 2085: thd-0x1a24000: amanda-rest-server: reading config file /usr/local/etc/amanda/amanda.conf
Mon Jan 15 19:14:50.378498217 2018: pid 2085: thd-0x1a24000: amanda-rest-server: running: starman /usr/local/libexec/amanda/rest-server/bin/app.pl --listen 127.0.0.1:9090 --preload-app   --max-requests 1 --daemonize --pid /tmp/amanda/rest-api-pid
Mon Jan 15 19:14:50.379230699 2018: pid 2086: thd-0x1a24000: amanda-rest-server: warning: Can't exec "starman": No such file or directory at /usr/local/sbin/amanda-rest-server line 126.
Mon Jan 15 19:14:50.379869308 2018: pid 2085: thd-0x1a24000: amanda-rest-server: Unable to start Amanda REST server

**Comment by martineau** [comment]
Install starman and the Dancer2 perl module
btw. Why do you want to run the REST server?

**Comment by Chetu-S-A** [comment]
Hey! That worked! Thanks a lot!
