### ISSUE TITLE
PROPOSED "NEW LOGO"

### ISSUE THREAD

**Issue by foways** [zmanda/amanda#87]
<h3>Hi, I am a graphic designer. </h3>

Here I have designed a logo of the "Amanda" pembahruan. I designed it very simple and minimalist, from the logo there is a special symbol of amanda, which has the symbol "a" and the symbol "BackUp". In color I just follow the theme than Amanda, here is the final result of the logo:

![last result of design](https://user-images.githubusercontent.com/38687140/39597264-07b6e7fa-4f3f-11e8-9319-b2b17ef2687d.png)

![model versions](https://user-images.githubusercontent.com/38687140/39597315-2e13e7ae-4f3f-11e8-93d4-a459c77bebd2.png)

![background version](https://user-images.githubusercontent.com/38687140/39597326-3671b8d6-4f3f-11e8-8093-e78784c6c02a.png)

<h2>I am awaiting feedback from you, and I am also willing to make improvements on request if possible.</h2>

<i>I will provide all the original files that can be edited after assessment.</i>

**Comment by stefangweichinger** [comment]
"bakcup" ? I would rethink that ;-)

**Comment by djmitche** [comment]
It's like "lite beer" or "cheeze".. no promises implied ;)

**Comment by chassell** [comment]
it is pretty ... but spelling may cownt.    (maybe that's the way to get "Exposure" out of it.. if accepted?)
